### ISSUE TITLE
[FEATURE] Display the questions and answers on the Content section

### ISSUE THREAD

**Issue by adamma1024** [BUMETCS673/seprojects-cs673a2f24_team5#10]
### 🎯 Feature Name

Display the questions and answers

### 🛠️ Problem Statement

The content section shows nothing currently.

### 💡 Describe the solution you'd like

- [ ] Add requests state: in_progress, succeed, failed
- [x] Add requests' interfaces. #26 
- [ ] Mock the data

**Comment by Linchen-Xu** [comment]
resolved in #32
